/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.efsdokmdfjkln;

import com.example.banquinho.service.serCli;
import org.junit.jupiter.api.BeforeEach;
import com.example.banquinho.service.serCon;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private serCon sercon;
    private serCli sercli;
    
    @BeforeEach
    void setUp() {
        long cpf = 12312312312L;
        sercli = new serCli();
        sercon = new serCon();
        sercli.Addcliente(cpf, "miguel");
        sercon.Addconta(0);
    }
    @Test
    void testDeposito() {
        double saldo = sercon.Deposito(0, 100);
        assertEquals(100, saldo);
    }
     @Test
    void testeDepositoNegativo() {
        Double retorno = sercon.Deposito(0, -100);
        assertNull(retorno);
    }
}

